import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/lib/auth/Provider";
import Navbar from "@/components/Navbar";
import TrpcProvider from "@/lib/trpc/Provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
<NextAuthProvider>
<TrpcProvider><main className="max-w-3xl mx-auto md:p-0 p-6">
<Navbar />
{children}
</main></TrpcProvider>
</NextAuthProvider>

<Toaster />
</ThemeProvider>
</body>
    </html>
  )
}
